### ISSUE TITLE
Smarties method does not work

### ISSUE THREAD

**Issue by srtll** [ilent2/ott#42]
Attempting to use either the GUI for "Geometric Shape T-matrix" or the command line "ott.Tmatrix.simple" fails when the user attempts to use the documented optional parameter 'method' with the value 'smarties'. The error is thrown by the ott.TmatrixSmarties function on line 123 indicating that method is not a recognized parameter. This seems like the parameter is getting passed down from the ott.Tmatrix.simple function to the subsidiary ott.TmatrixSmarties function when it shouldn't be but I am unfamiliar with the object oriented programming approach in Matlab so I may be wrong here. It is also possible this errror is somehow due to smarties not being installed but, if so, the error does not seem to alert the user to that effect. (I did, in fact, install smarties and used the initpath function to add it to my path prior to running ott.) This error was seen using Matlab R2019b on Mac OS Catalina.

**Comment by ilent2** [comment]
Hi @srtll ,

Thanks for reporting the problem, I've just pushed a new commit to GitHub that should hopefully fix the problem.  The Tmatrix.simple method is a little messy and it will be changing in version 2 so that these sorts of issues don't keep popping up.  

Version 2 will also make it slightly easier to include Smarties as well: you won't have to download it separately, hopefully making it a little easier to use.

I'll push a minor release to the file exchange in a minute (not sure if you are using the GitHub version or the file exchange version).

Cheers -- Isaac
