### ISSUE TITLE
The refractive index of a medium varies with the laser of different wavelength

### ISSUE THREAD

**Issue by wj2392907320** [ilent2/ott#49]
Does the program take into account the effect of different laser wavelengths on the refractive index of the medium (such as water)? Since the refractive index of most media is corresponding to the refractive index of D-light (589.3nm), while optical tweezers are commonly used for 1064nm laser, the corresponding refractive index of media will decrease somewhat at 1064nm band, resulting in slightly different results.
   Thank you, Dr. Lenton

**Comment by ilent2** [comment]
Hi,

The code should work fine for different non-absorbing external media, you just need to supply the light wavelength and refractive index of the medium for the T-matrix calculation.  The code should also give reasonable estimates for the force in weakly absorbing media, but the medium refractive index supplied to the functions needs to be a real number.

However, for water between 580nm and 1064nm, I'm not sure if you will see a difference in the results since the difference is fairly small and might be less than the calculation error (depending on the shape you are calculating the T-matrix for).

Best,
Isaac

**Comment by wj2392907320** [comment]
Dear Dr. Lenton
As you said, the difference is small. I investigated the refractive index of water against different wavelengths, and obtained that the refractive index of water is 1.334 at 580nm and 1.325 at 1060nm. The simulation results are shown in the figure below. The wavelength used is 1064, NA=1.2, and the diameter of the microsphere is 2 microns. 
<img width="840" alt="image" src="https://user-images.githubusercontent.com/46819715/209747989-8589cbc3-91e0-49bd-84d5-61c9a9766045.png">

Best wishes
Wang jing
